data:
  annotation: clipping_points.json
  data_path: E:\__RCA_bif_detection\data\*
  dataset_csv: D:\ai intro\Angiografii\PROIECT_ANGIOGRAFII\CSV_angiografii.csv
  img_size:
  - 256
  - 256
  split_per:
    test: 0.1
    train: 0.8
    valid: 0.1
test:
  threshold: 0.5
train:
  alpha:
  - 0.6
  - 0.8
  bs: 4
  contrast_gamma:
  - 1.5
  - 2
  contrast_prob: 0.5
  epochs: 500
  flip_prob: 0.5
  flip_spatial_axis: 1
  gibbs_noise_prob: 0.5
  lr: 0.001
  max_zoom: 1.5
  min_zoom: 1.3
  opt: Adam
  rotate_prob: 0.5
  rotate_range: 1.57
  sigma:
  - 0.1
  - 1
  zoom_prob: 0.5
