data:
  dataset_csv: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\CSV_angiografii.csv"
  data_path: "E:\\__RCA_bif_detection\\data\\*"
  annotation: clipping_points.json
  img_size: [256,256]
  split_per:
    train: 0.8
    valid: 0.1
    test: 0.1

train:
  bs:  8
  lr: 0.001
  opt: Adam
  epochs: 100
  rotate_prob: 1
  rotate_range: [1]
  flip_prob : 1.0 
  flip_spatial_axis: 1.0
  rand_crop_samples: 4 
  rand_crop_size: [100, 100, 100]
  sigma: 1.0 
  # sigma: [0.1,1] 
  # kernel_size: [9, 9]
  # rotation_degrees_top: 360
  # rotation_degrees_bottom: 0
  # flip_probability: 0.5


test:
  threshold: 0.5
