data:
  dataset_csv: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\CSV_angiografii.csv"
  data_path: "E:\\__RCA_bif_detection\\data\\*"
  annotation: clipping_points.json
  img_size: [256,256]
  split_per:
    train: 0.8
    valid: 0.1
    test: 0.1

train:
  bs: 8
  lr: 0.0001
  opt: Adam
  epochs: 200
  rotate_prob: 0.5
  rotate_range: 1
  flip_prob : 0.5
  flip_spatial_axis: 1
  sigma: [0.1,1] 
  zoom_prob: 1
  min_zoom: 1.3
  max_zoom: 1.5


test:
  threshold: 0.5
