data:
  frame: "D:\\ai intro\\Angiografii\\20100131_114101_plane\\frame_extractor_frames.npz"
  vasselness: "D:\\ai intro\\Angiografii\\20100131_114101_plane\\vesselness_heatmaps.npz"
  annotation: clipping_points.json
  img_size: [256,256]
  split_per:
    train: 0.8
    valid: 0.1
    test: 0.1

train:
  bs: 8
  lr: 0.001
  opt: Adam
  epochs: 100

test:
  threshold: 0.5
