data:
  dataset_csv: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\CSV_angiografii.csv"
  data_path: "E:\\__RCA_bif_detection\\data\\*"
  annotation: clipping_points.json
  exp: "experiments"
  parent_dir_exp: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\experiments\\EXPERIMENTE\\Experiment_Dice_index12052022_1338"
  model: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\experiments\\EXPERIMENTE\\Experiment_Dice_index12052022_1338\\Weights\\my_model12072022_0114_e450.pt"
  img_size: [256,256]
  split_per:
    train: 0.8
    valid: 0.1
    test: 0.1

train:
  bs: 2
  lr: 0.001
  opt: Adam
  epochs: 500
  rotate_prob: 0.5
  rotate_range: 35 
  clip_limit: 4 
  tile_grid_size: [8, 8] 
  p_clahe: 0.5
  blur_limit: [1, 3] 
  sigma_limit: 0
  p_gauss_blur: 0.5
  gamma_limit: [80, 120]
  p: 0.5

  


test:
  threshold: 0.5


