data:
  dataset_csv: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\CSV_angiografii.csv"
  data_path: "E:\\__RCA_bif_detection\\data\\*"
  annotation: clipping_points.json
  parent_dir_exp: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\experiments\\Expetimente_Segmentare\\Experiment_Dice_index02082023_1813"
  model: "D:\\ai intro\\Angiografii\\PROIECT_ANGIOGRAFII\\experiments\\Expetimente_Segmentare\\Experiment_Dice_index02082023_1813\\Weights\\my_model02102023_1709_e350.pt"
  img_size: [512,512]
  split_per:
    train: 0.8
    valid: 0.1
    test: 0.1

train:
  bs: 4
  lr: 0.001
  opt: Adam
  epochs: 400
  rotate_prob: 0.5
  rotate_range: 1.57
  flip_prob : 0.5
  flip_spatial_axis: 1
  sigma: [0.1,1] 
  gibbs_noise_prob: 0.5
  contrast_prob: 0.5
  contrast_gamma: [1.5,2]
  alpha: [0.6,0.8]
  zoom_prob: 0.5
  min_zoom: 1.3
  max_zoom: 1.5


test:
  threshold: 0.5
